config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about' => 'home#about', :as => 'about'
  get '/help' => 'home#help', :as => 'help'
  
  devise_for :users, :path => 'u',:controllers => { :registrations => "users_registrations", :sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :users do
    member do
      put 'enable'
      put 'disable'
      put 'disable_and_reset'
    end
    collection do
      get 'stats'
    end
    resource :user_account
    resources :roles
  end
  
  get '/maps/activity' => 'audits#for_map_model', :as => "maps_activity"
  
  resources :maps  do
    member do
      get 'map_type'
      get 'export'
      get 'warp'
      get 'clip'
      post 'rectify'
      get 'align'
      get 'warped'
      get 'metadata'
      get 'comments'
      get 'delete'
      get 'status'
      get 'publish'
      get 'unpublish'
      post 'save_mask_and_warp'
      delete 'delete_mask'
      post 'warp_aligned'
      get 'gcps'
      get 'rough_state' => 'maps#get_rough_state'
      post 'rough_state' => 'maps#set_rough_state'
      get 'rough_centroid'=> 'maps#get_rough_centroid'
      post 'rough_centroid' => 'maps#set_rough_centroid'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do
        get 'geosearch'
        get 'tag'
    end
    resources :layers
  end
  
  get '/maps/thumb/:id' => 'maps#thumb', :as =>'thumb_map'
  
  get '/gcps/' => 'gcp#index', :as => "gcps"
  get '/gcps/:id' => 'gcps#show', :as => "gcp"
  delete '/gcps/:id/destroy' => 'gcps#destroy', :as => "destroy_gcp"
  post '/gcps/add/:mapid' => 'gcps#add', :as => "add_gcp"
  put '/gcps/update/:id' => 'gcps#update', :as => "update_gcp"
  put '/gcps/update_field/:id' => 'gcps#update_field', :as => "update_field_gcp"
  

  get '/maps/wms/:id' => "maps#wms", :as => 'wms_map'
  get '/maps/tile/:id/:z/:x/:y' => "maps#tile", :as => 'tile_map'
  
  get '/layers/wms/:id' => "layers#wms", :as => "wms_layer"
  get '/layers/tile/:id/:z/:x/:y' => "layers#tile", :as => 'tile_layer'
  
  resources :layers do
    member do
      get 'comments'
      get 'merge'
      get 'publish'
      get 'toggle_visibility'
      post 'update_year'
      get 'wms'
      get 'wms2'
      get 'maps'
      get 'export'
      get 'metadata'
      get 'delete'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do 
      get 'geosearch'
    end
  end
  
  put '/layers/:id/remove_map/:map_id' => 'layers#remove_map', :as => 'remove_layer_map'
  put '/layers/:id/merge' => 'layers#merge', :as => 'do_merge_layer'
  
  get '/users/:user_id/maps' => 'my_maps#list', :as => 'my_maps'
  post '/users/:user_id/maps/create/:map_id' => 'my_maps#create', :as => 'add_my_map'
  post '/users/:user_id/maps/destroy/:map_id' => 'my_maps#destroy', :as => 'destroy_my_map'

  get '/users/:id/activity' => 'audits#for_user', :as => 'user_activity'
  
  
  get '/maps/acitvity.:format' => 'audits#for_map_model', :as => "formatted_maps_activity"
  get '/maps/:id/activity' => 'audits#for_map', :as => "map_activity"
  get '/maps/:id/activity.:format' => 'audits#for_map', :as => "formatted_map_activity"

  get '/activity' => 'audits#index', :as => "activity"
  get '/activity/:id' => 'audits#show', :as => "activity_details"
  get '/activity.:format' => 'audits#index', :as => "formatted_activity"

  
  resources :comments

  
  resources :groups 
  
  get '/groups/:group_id/users/new' => 'memberships#new', :as => 'new_group_user'
  delete '/groups/:group_id/users/destroy/:id' => 'memberships#destroy', :as => 'destroy_group_user'
  get '/groups/:group_id/users' => 'users#index_for_group', :as => 'group_users'
  get '/groups/:group_id/map' => 'maps#index_for_map', :as => 'group_maps'

  resources :imports do
    member do
      get 'maps'
      get 'start'
      get 'status'
    end
  end
   
  

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  layout 'mapdetail', :only => [:show, :edit, :preview, :warp, :clip, :align, :activity, :warped, :export, :metadata, :comments]
  
  before_filter :store_location, :only => [:warp, :align, :clip, :export, :edit, :comments ]
  
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy, :delete, :warp, :rectify, :clip, :align, :warp_align, :mask_map, :delete_mask, :save_mask, :save_mask_and_warp, :set_rough_state, :set_rough_centroid, :publish, :trace, :id]
 
  before_filter :check_administrator_role, :only => [:publish]
 
  before_filter :find_map_if_available,
    :except => [:show, :index, :wms, :tile, :mapserver_wms, :warp_aligned, :status, :new, :create, :update, :edit, :tag, :geosearch]

  before_filter :check_link_back, :only => [:show, :warp, :clip, :align, :warped, :export, :activity]
  before_filter :check_if_map_is_editable, :only => [:edit, :update]
  before_filter :check_if_map_can_be_deleted, :only => [:destroy, :delete]
  skip_before_filter :verify_authenticity_token, :only => [:save_mask, :delete_mask, :save_mask_and_warp, :mask_map, :rectify, :set_rough_state, :set_rough_centroid]
  
  rescue_from ActiveRecord::RecordNotFound, :with => :bad_record

  helper :sort
  include SortHelper
  
  ###############
  #
  # CRUD
  #
  ###############
  
  def new
    @map = Map.new
    @html_title = "Upload a new map to "
    @max_size = Map.max_attachment_size
    if Map.max_dimension
      @upload_file_message  = " It may resize the image if it's too large (#{Map.max_dimension}x#{Map.max_dimension}) "
    else
      @upload_file_message = ""
    end

    respond_to do |format|
      format.html{ render :layout =>'application' }  # new.html.erb
      format.xml  { render :xml => @map }
    end
  end
  
  def create
    @map = Map.new(map_params)

    if user_signed_in?
      @map.owner = current_user
      @map.users << current_user
    end

    respond_to do |format|
      if @map.save
        flash[:notice] = 'Map was successfully created.'
        format.html { redirect_to(@map) }
        format.xml  { render :xml => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new", :layout =>'application' }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @current_tab = :edit
    @selected_tab = 1
    @html_title = "Editing Map #{@map.title} on"
    choose_layout_if_ajax
    respond_to do |format|
      format.html {} #{ render :layout =>'application' }  # new.html.erb
      format.xml  { render :xml => @map }
    end
  end
  
  def update
   
    if @map.update_attributes(map_params)
      flash.now[:notice] = 'Map was successfully updated.'
    else
      flash.now[:error] = 'There was an error updating the map' 
    end
    
    if request.xhr?
      @xhr_flag = "xhr"
      render :action => "edit", :layout => "tab_container"
    else
      respond_to do |format|
        format.html { redirect_to map_path }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
    
  end
  
  def delete
    respond_to do |format|
      format.html {render :layout => 'application'}
    end
  end
  
  #only editors or owners of maps
  def destroy
    if @map.destroy
      flash[:notice] = "Map deleted!"
    else
      flash[:notice] = "Map wasnt deleted"
    end
    respond_to do |format|
      format.html { redirect_to(maps_url) }
      format.xml  { head :ok }
    end
  end
  
  ###############
  #
  # Collection actions 
  #
  ###############
  def index
    sort_init('updated_at', {:default_order => "desc"})
    
    sort_update
    @show_warped = params[:show_warped]
    request.query_string.length > 0 ?  qstring = "?" + request.query_string : qstring = ""
    
    set_session_link_back url_for(:controller=> 'maps', :action => 'index',:skip_relative_url_root => false, :only_path => false )+ qstring
    
    @query = params[:query]
    
    @field = %w(tags title description status publisher authors).detect{|f| f == (params[:field])}
    
    unless @field == "tags"
      
      @field = "title" if @field.nil?
      
      #we'll use POSIX regular expression for searches    ~*'( |^)robinson([^A-z]|$)' and to strip out brakets etc  ~*'(:punct:|^|)plate 6([^A-z]|$)';
      if @query && @query.strip.length > 0 && @field
        conditions = ["#{@field}  ~* ?", '(:punct:|^|)'+@query+'([^A-z]|$)']
      else
        conditions = nil
      end
      
      if params[:sort_order] && params[:sort_order] == "desc"
        sort_nulls = " NULLS LAST"
      else
        sort_nulls = " NULLS FIRST"
      end
      @per_page = params[:per_page] || 10
      paginate_params = {
        :page => params[:page],
        :per_page => @per_page
      }
      order_options = sort_clause + sort_nulls
      where_options = conditions
      #order('name').where('name LIKE ?', "%#{search}%").paginate(page: page, per_page: 10)

      if @show_warped == "1"
        @maps = Map.warped.are_public.where(where_options).order(order_options).paginate(paginate_params)
      elsif @show_warped == "1" && (user_signed_in? and current_user.has_role?("editor"))
        @maps = Map.warped.where(where_options).order(order_options).paginate(paginate_params)
      elsif  @show_warped != "1" && (user_signed_in? and current_user.has_role?("editor"))
        @maps = Map.where(where_options).order(order_options).paginate(paginate_params)
      else
        @maps = Map.are_public.where(where_options).order(order_options).paginate(paginate_params)
      end
      
      @html_title = "Browse Maps"
      if request.xhr?
        render :action => 'index.rjs'
      else
        respond_to do |format|
          format.html{ render :layout =>'application' }  # index.html.erb
          format.xml  { render :xml => @maps.to_xml(:root => "maps", :except => [:content_type, :size, :bbox_geom, :uuid, :parent_uuid, :filename, :parent_id,  :map, :thumbnail, :rough_centroid]) {|xml|
              xml.tag!'stat', "ok"
              xml.tag!'total-entries', @maps.total_entries
              xml.tag!'per-page', @maps.per_page
              xml.tag!'current-page',@maps.current_page} }
          
          format.json { render :json => {:stat => "ok",
              :current_page => @maps.current_page,
              :per_page => @maps.per_page,
              :total_entries => @maps.total_entries,
              :total_pages => @maps.total_pages,
              :items => @maps.to_a}.to_json(:except => [:content_type, :size, :bbox_geom, :uuid, :parent_uuid, :filename, :parent_id,  :map, :thumbnail, :rough_centroid], :methods => :depicts_year) , :callback => params[:callback]
          }
        end
      end
    else
      redirect_to :action => 'tag', :id => @query
    end
  end
  
    
  def tag
    sort_init('updated_at', {:default_order => "desc"})
    sort_update
    @tags = params[:id] || @query
    @html_title = "Maps tagged with #{@tags} on "
    @maps = Map.are_public.order(sort_clause).tagged_with(@tags).paginate(
      :page => params[:page],
      :per_page => 20)
    respond_to do |format|
      format.html { render :layout =>'application' }  # index.html.erb
      format.xml  { render :xml => @maps }
      format.rss  { render  :layout => false }
    end
  end
  
    
  def geosearch
    require 'geoplanet'
    sort_init 'updated_at'
    sort_update

    extents = [-74.1710,40.5883,-73.4809,40.8485] #NYC

    #TODO change to straight javascript call.
    if params[:place] && !params[:place].blank?
      place_query = params[:place]
      GeoPlanet.appid = APP_CONFIG['yahoo_app_id']
      
      geoplanet_result = GeoPlanet::Place.search(place_query, :count => 2)
      
      if geoplanet_result[0]
        g_bbox =  geoplanet_result[0].bounding_box.map!{|x| x.reverse}
        extents = g_bbox[1] + g_bbox[0]
        render :json => extents.to_json
        return
      else
        render :json => extents.to_json
        return
      end
    end

    if params[:bbox] && params[:bbox].split(',').size == 4
      begin
        extents = params[:bbox].split(',').collect {|i| Float(i)}
      rescue ArgumentError
        logger.debug "arg error with bbox, setting extent to defaults"
      end
    end
    @bbox = extents.join(',')

    if extents
      bbox_poly_ary = [
        [ extents[0], extents[1] ],
        [ extents[2], extents[1] ],
        [ extents[2], extents[3] ],
        [ extents[0], extents[3] ],
        [ extents[0], extents[1] ]
      ]

      bbox_polygon = GeoRuby::SimpleFeatures::Polygon.from_coordinates([bbox_poly_ary], -1).as_ewkt
      if params[:operation] == "within"
        conditions = ["ST_Within(bbox_geom, ST_GeomFromText('#{bbox_polygon}'))"]
      else
        conditions = ["ST_Intersects(bbox_geom, ST_GeomFromText('#{bbox_polygon}'))"]
      end

    else
      conditions = nil
    end


    if params[:sort_order] && params[:sort_order] == "desc"
      sort_nulls = " NULLS LAST"
    else
      sort_nulls = " NULLS FIRST"
    end


      @operation = params[:operation]

    if @operation == "intersect"
      sort_geo = "ABS(ST_Area(bbox_geom) - ST_Area(ST_GeomFromText('#{bbox_polygon}'))) ASC,  "
    else
      sort_geo ="ST_Area(bbox_geom) DESC ,"
    end

    paginate_params = {
      :page => params[:page],
      :per_page => 20
    }
    order_params = sort_geo + sort_clause + sort_nulls
    @maps = Map.select("bbox, title, description, updated_at, id, date_depicted").warped.where(conditions).order(order_params).paginate(paginate_params)
    @jsonmaps = @maps.to_json # (:only => [:bbox, :title, :id, :nypl_digital_id])
    respond_to do |format|
      format.html{ render :layout =>'application' }
      
      format.json { render :json => {:stat => "ok",
        :current_page => @maps.current_page,
        :per_page => @maps.per_page,
        :total_entries => @maps.total_entries,

app/views/maps/clip.html.erb
<% content_for :head do  %>
  <script  type="text/javascript">
    var map_id = '<%=h @map.id -%>';
    var title = 'clipping map';
    var gml_file_exists = <%= @gml_exists %>;
    var timestamp = Math.round(new Date().getTime() / 1000.0);

    var gml_url = "<%=request.protocol + request.host_with_port-%>/mapimages/<%= @map.id%>" + ".gml.ol?" + timestamp;
      var clip_image_width = <%= @map.width %>;
      var clip_image_height = <%= @map.height %>;
      var clip_wms_url = '<%= url_for :controller => 'maps', :action => 'wms', :id => @map  -%>';
      jQuery(document).ready(function() {
        jQuery('#popoverNotice2').hide();
      });

  </script>
  <%= javascript_include_tag "clip" %>
<% end -%>
<% @onload =  "clipinit();" -%>

<div id="clipmap">
</div>
<div id="popoverNotice2" class="hidden-at-start"><%= image_tag "spinner.gif" %><span id="noticeMessage2"> </span></div>
<div id="maskresult"></div>

<div id="cliphelp">
  <p>1. Draw around the area you wish to keep.  </p>
  <p>2. Then to apply the mask to the map, click "Mask Map!" </p>
</div>

<div id="info">
  <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery("form#clip_form2").bind("ajax:success", function(e, data, status, xhr) {
        jqHighlight('maskresult');
        jQuery("#maskresult").html(data.message);
      }).bind("ajax:before", function() {
        deselect();
        bigModalDialog2('<br />Saving mask...<br />Cropping map...');
        serialize_features();
      }).bind("ajax:complete", function() {
        closeBigModalDialog2();
        updateOtherMaps();
      });
    });
  </script>
  <%= form_tag save_mask_and_warp_map_path(@map.id, :format=>"json"), :remote => true, :id => 'clip_form2' do %>
    <%= hidden_field_tag "output" %>
    <%= submit_tag "Mask Map!" %>
  <% end %>

  <br />
  <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery("a#delete_mask").bind("ajax:success", function(e, data, status, xhr) {
        jqHighlight('maskresult');
        jQuery("#maskresult").html(data.message);
        destroyMask();
      }).bind("ajax:complete", function() {
        updateOtherMaps();
      }).bind("ajax:error", function() {
        alert('that didnt work as expected, sorry');
      });
    });
  </script>

  <%= link_to("Delete mask", delete_mask_map_path(:id=>@map.id, :format=>"json"), :id => "delete_mask", :class=>"delete_button", :remote => true,  :method => "delete",  data: { confirm: 'Really delete mask and start over?'})%>


</div>

app/views/maps/comments.html.erb
<h2> Comments </h2>
<%unless @comments.empty? -%>
  <%= render :partial => 'comments/comment', :collection => @comments %>
<% else -%>
  There's no comments for this map, why not add one now! <br />
<% end -%>
<% if user_signed_in? %>
  <%= render :partial => 'comments/comment_form', :object => @map, as: 'comment_obj' -%>
<% else -%>
  <%= link_to "Log in to add a comment", new_user_session_path() %> 
<% end -%>

app/views/maps/edit.html.erb
<h2>Editing Map Attributes</h2>

<%= error_messages_for @map %>

<%- if (current_user = @map.owner || admin_authorized?) -%>
   <p>&mdash; <%=  link_to 'Delete this map.', delete_map_path(@map)  %> &mdash; </p>
<% end %>

<%= render :partial => "form_remote", :locals => {:page => "edit"} %>

app/views/maps/export.html.erb
<h2>Map</h2>
<ul>
  <li>
    GeoTiff: <%= link_to  "Download rectified GeoTiff", export_map_url(:id => @map, :format => :tif) %>
  </li>
  <li>
    PNG: <%= link_to  "Download rectified PNG", export_map_url(:id => @map, :format => :png) %>
    (and associated <%= link_to ".aux.xml", export_map_url(:id => @map, :format => :aux_xml) %> file)
  </li>
</ul>

<ul>
  <li>KML: <%= link_to("Download KML file",  map_url(:id => @map, :format => :kml)) %>
    (<%= link_to("View KML in Google Maps", "http://maps.google.com?q="+map_url(:id => @map, :format => :kml), :target => "_blank") %> )</li>
  <li>
    <% josm_url = url_for(wms_map_url(:id => @map)) + "?request=GetMap&version=1.1.1&styles=&format=image/png&srs={proj}&exceptions=application/vnd.ogc.session.inimage&width={width}&height={height}&BBOX={bbox}&" %>
    WMS: <%= link_to("WMS Capabilities URL", url_for(wms_map_url(:id=>@map, :request => "GetCapabilities", :service => "WMS", :version => "1.1.1")) )%>
    (<%= link_to "for JOSM OpenStreetMap Editor", josm_url %>    )
  </li>
  <li>
    <% tile_url = url_for("/maps/tile/{z}/{x}/{y}.png") %>
    Tiles (Google/OSM scheme): <%= tile_url %>
  </li>
</ul>
Bibliographic:
<ul>
  <li>
    <%= link_to 'Bibliographic', "http://example.com/alink"  %>
  </li>
</ul>

app/views/maps/trace.html.erb
<table id="map_table">
  <% overlay_partial = @overlay.class == Map ? 'maps/map_detail' : 'layers/layer_detail' %>
  <%= render :partial => overlay_partial, :object => @overlay, :locals => {:variety => "detail"} %>

</table>
<% if !APP_CONFIG["id_key"].blank? %>
  <div id="id-map">
    <iframe frameBorder="0" id="id-embed" class="id-embed"></iframe>
  </div>
  <script>
    var params = {};
    
    <% bounds = @overlay.class == Map ? @overlay.bounds : @overlay.get_bounds %>
    var map_bounds = new OpenLayers.Bounds(<%=bounds-%>);

    var map_center = map_bounds.getCenterLonLat();
  
    <% if @lat && @lon -%>
      params.map = '16/<%= @lon %>/<%= @lat %>';
    <% else -%>
      params.map = '16/'+map_center.lon+'/'+map_center.lat;
    <% end -%>
    
  <% if @overlay.class == Map %>
    $('#id-embed').attr('src', '<%= id_map_url :locale => params[:locale] %>#'+ querystring.stringify(params));
  <% else %>
    $('#id-embed').attr('src', '<%= id_layer_url :locale => params[:locale] %>#'+ querystring.stringify(params));
  <% end %>
  </script>
<% else %>
  <script type="text/javascript">alert("Sorry iD is not configured.")</script>
<% end %>

app/views/maps/warp.html.erb
<% content_for :head do %>
  <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
  <script type="text/javascript" charset="utf-8">
    var icon_imgPath = '/assets/icons/';
    var gcp_add_url = "<%= url_for add_gcp_path :mapid=> @map %>";
    var gcp_update_url = "/gcps/update";
    var gcp_update_field_url = "/gcps/update_field";

    var from_map;
    var to_map;
    var gcp_markers = new Array(); // an array
    var map_id = '<%=h @map.id -%>';
    var title = '<%=u @map.title -%>';
    var image_width = <%= @map.width %>;
    var image_height = <%= @map.height %>;
    var wms_url = '<%= url_for :controller => 'maps', :action => 'wms', :id => @map  -%>';
    var empty_wms_url = '<%= url_for :controller => 'maps', :action => 'wms' -%>';
    var map_has_bounds = false;
    var layer_baseurl = '<%=url_for :controller => 'layers', :action => 'wms' %>';
    var layers_array = [<%=@other_layers.join(",")-%>];
    var map_bounds = new OpenLayers.Bounds();
  <% if @map.gcps.hard.size > 0 %>
      map_bounds = new OpenLayers.Bounds(<%=@map.bounds-%>);
      map_has_bounds = true;
      map_center = map_bounds.getCenterLonLat();
  <% end %>
    //set up jquery for the hidden tables
    jQuery(document).ready(function() {
      jQuery('#popoverNotice').hide();
      jQuery('#gcp_table_div').hide();
      jQuery('#advanced_form_options').hide();

      jQuery('#controlPointLink').click(function() {
        jQuery('#gcp_table_div').toggle('slow');
        return false;
      });
      jQuery('#advancedLink').click(function() {
        jQuery('#advanced_form_options').toggle('slow');
        return false;
      });
      jQuery('#to_map_notify_close>a').click(function() {
        jQuery('#to_map_notification').hide('slow');
        return false;
      });
    });

  </script>

  <%= javascript_include_tag "warp"-%>

  <script  type="text/javascript">
    function popul() {
  <% @gcps.each do |gcp| -%>
        populate_gcps(<%=gcp.id-%>, <%= gcp.x -%>, <%= gcp.y -%>, <%= gcp.lon -%>, <%= gcp.lat -%>, <%=gcp.error -%>);
  <% end -%>
      update_row_numbers();

  <% if @bestguess_places -%>
        var bestGuessResult = <%= @bestguess_places.to_json.html_safe -%>;
        bestGuess(bestGuessResult);
  <% end -%>

    }
  </script>

<% end -%>

<% @onload="init();popul();" -%>

<div id ="from_map_block">
  <div id="from_map" class="map-off"></div>
  <span class="tie_button"></span>
</div>
<div id="link-map-button" class="link-map-button-off"
     onclick="toggleJoinLinks();" title="Pan/zoom lock" ></div>

<div id = "to_map_block">
  <div id="to_map_notification" class="hidden"><div id="to_map_notify_close"><a href="#" title="Close popup">X</a></div><div id="to_map_notification_inner"></div> </div>
  <div id="to_map" class="map-off"></div>
  <div id="warped-slider"><div class="ui-slider-handle"></div></div>
</div>
<div id="popoverNotice" class="hidden-at-start"><%= image_tag "spinner.gif" %><span id="noticeMessage"></span></div>
<!--
<div id = "add_layer_control" onClick="Element.show('add_layer');">Add layer</div>
<div id = "add_layer" style="display:none;">

  <form onSubmit="addLayerToDest(this);return false;" action="">
    Enter in number of warped map to add <input type="text" name="layer_num" id="layer_num" />
  </form>
<a class="fake_link" onClick="Element.hide('add_layer');">hide</a></div>
-->
<div id="gcp">
  <em>Double-click on both maps, then click</em>
  <div id="addPointDiv" class="addPoint"><input type="button" id="GcpButton" value="Add Control Point" onclick="set_gcp();" class="gcp_button" /></div>.
  <em> Do this for at least three points.</em></div>

<fieldset id="control_panel_fieldset">

  <legend>Control Panel</legend>
  <div id="rectifyNotice">
    <span id="spinner" style="display:none;"><%= image_tag 'spinner.gif' %></span><span id="gcp_notice"></span>
  </div>
  <a href="#" id="controlPointLink">Control Points</a>
  <div id = "div_gcp_form">
    <%= form_for(:gcp, {:html => {:id => 'gcp_form'} ,  :url =>rectify_map_path(@map), :remote => true }) do |f| %>
      <div id="gcp_table_div" >
        <table id="gcp_table" class="gcpTabClass">

          <thead>
            <tr><th>Point</th><th>Image X</th><th>Image Y</th><th>Lon</th><th>Lat</th><th id="errortitle">Error(<%=sprintf("%.2f",@map.error) %>)</th><th></th>
            </tr>
          </thead>
          <tbody id="gcp_list">
            <%= render(:partial => "gcps/gcp", :collection => @gcps) %>
          </tbody>
        </table>
        <input type="button" value="Add Control Point Manually" onclick="save_new_gcp(0, 0, 0, 0);" />
      </div>

      <input type="hidden" name="map" value ="<%= @map.id %>" />
      <a href="#" id="advancedLink">Advanced options</a>
      <div id="advanced_form_options" >
        Rectify Method:
        <select name="transform_options">
          <option value="auto" selected="selected">Auto - based on number of control points (default)</option>
          <option value="p1">1st Order Polynomial (min 3 points)</option>
          <option value="p2">2nd Order Polynomial (min 6 points)</option>
          <option value="p3">3rd Order Polynomial (min 10 points)</option>
          <option value="tps">Thin Plate Spline (many points widely spread)</option> <!-- tps could be unsuitable for this style of rectification? needs a good spread of gcps anyhow. -->
        </select>
        <br />
        Resampling Method:
        <select name="resample_options">
          <option value="near" selected="selected">Nearest Neighbour, fastest (default)</option>
          <option value="bilinear">Bilinear</option>
          <option value="cubic">Cubic</option>
          <option value="cubicspline">Cubic Spline , slower but best quality</option>
          <!-- <option value="lanczos">Lanczos</option> this is very very slow -->
        </select>
      </div>
      <p>
        
   <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery("form#gcp_form").bind("ajax:before", function(event, data, status, xhr) {
        if (event.target.id == "gcp_form"){
          bigModalDialog('Rectifying.....');
        }
      }).bind("ajax:error", function(){
        gcp_notice('Sorry, there appears to be an error sending the request to the server, try again?...');  
      });
    });
  </script>
        <%= f.submit 'Warp Image! &rarr;'.html_safe, {:class  => "warp_button", :id=>"warp_button"}%>
      </p>
      <div id ="clipping_mask_buttons">

        <% if @map.mask_status.nil? || @map.mask_status == :unmasked -%>
          This map either is not currently masked. Do you want to <%= link_to "add or edit a mask now", map_path(:id =>@map, :anchor=>"Crop_tab") %>? <br />
        <% end %>
        Apply <%= link_to "clipping mask", map_path(:id =>@map, :anchor=>"Crop_tab") %> when rectifying?
        <label for="use_mask1">
          <input <% if @map.mask_status == :masked -%>checked<%end-%> id="use_mask1" type="radio" name="use_mask" value="true" />Yes
        </label>
        <label for="use_mask2">
          <input <% if @map.mask_status == :unmasked -%>checked<%end-%> name="use_mask" id="use_mask2" type="radio" value="false" />No
        </label>
      </div>

    <% end %>
  </div>
</fieldset>