config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about' => 'home#about', :as => 'about'
  get '/help' => 'home#help', :as => 'help'
  
  devise_for :users, :path => 'u',:controllers => { :registrations => "users_registrations", :sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :users do
    member do
      put 'enable'
      put 'disable'
      put 'disable_and_reset'
    end
    collection do
      get 'stats'
    end
    resource :user_account
    resources :roles
  end
  
  get '/maps/activity' => 'audits#for_map_model', :as => "maps_activity"
  
  resources :maps  do
    member do
      get 'map_type'
      get 'export'
      get 'warp'
      get 'clip'
      post 'rectify'
      get 'align'
      get 'warped'
      get 'metadata'
      get 'comments'
      get 'delete'
      get 'status'
      get 'publish'
      get 'unpublish'
      post 'save_mask_and_warp'
      delete 'delete_mask'
      post 'warp_aligned'
      get 'gcps'
      get 'rough_state' => 'maps#get_rough_state'
      post 'rough_state' => 'maps#set_rough_state'
      get 'rough_centroid'=> 'maps#get_rough_centroid'
      post 'rough_centroid' => 'maps#set_rough_centroid'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do
        get 'geosearch'
        get 'tag'
    end
    resources :layers
  end
  
  get '/maps/thumb/:id' => 'maps#thumb', :as =>'thumb_map'
  
  get '/gcps/' => 'gcp#index', :as => "gcps"
  get '/gcps/:id' => 'gcps#show', :as => "gcp"
  delete '/gcps/:id/destroy' => 'gcps#destroy', :as => "destroy_gcp"
  post '/gcps/add/:mapid' => 'gcps#add', :as => "add_gcp"
  put '/gcps/update/:id' => 'gcps#update', :as => "update_gcp"
  put '/gcps/update_field/:id' => 'gcps#update_field', :as => "update_field_gcp"
  

  get '/maps/wms/:id' => "maps#wms", :as => 'wms_map'
  get '/maps/tile/:id/:z/:x/:y' => "maps#tile", :as => 'tile_map'
  
  get '/layers/wms/:id' => "layers#wms", :as => "wms_layer"
  get '/layers/tile/:id/:z/:x/:y' => "layers#tile", :as => 'tile_layer'
  
  resources :layers do
    member do
      get 'comments'
      get 'merge'
      get 'publish'
      get 'toggle_visibility'
      post 'update_year'
      get 'wms'
      get 'wms2'
      get 'maps'
      get 'export'
      get 'metadata'
      get 'delete'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do 
      get 'geosearch'
    end
  end
  
  put '/layers/:id/remove_map/:map_id' => 'layers#remove_map', :as => 'remove_layer_map'
  put '/layers/:id/merge' => 'layers#merge', :as => 'do_merge_layer'
  
  get '/users/:user_id/maps' => 'my_maps#list', :as => 'my_maps'
  post '/users/:user_id/maps/create/:map_id' => 'my_maps#create', :as => 'add_my_map'
  post '/users/:user_id/maps/destroy/:map_id' => 'my_maps#destroy', :as => 'destroy_my_map'

  get '/users/:id/activity' => 'audits#for_user', :as => 'user_activity'
  
  
  get '/maps/acitvity.:format' => 'audits#for_map_model', :as => "formatted_maps_activity"
  get '/maps/:id/activity' => 'audits#for_map', :as => "map_activity"
  get '/maps/:id/activity.:format' => 'audits#for_map', :as => "formatted_map_activity"

  get '/activity' => 'audits#index', :as => "activity"
  get '/activity/:id' => 'audits#show', :as => "activity_details"
  get '/activity.:format' => 'audits#index', :as => "formatted_activity"

  
  resources :comments

  
  resources :groups 
  
  get '/groups/:group_id/users/new' => 'memberships#new', :as => 'new_group_user'
  delete '/groups/:group_id/users/destroy/:id' => 'memberships#destroy', :as => 'destroy_group_user'
  get '/groups/:group_id/users' => 'users#index_for_group', :as => 'group_users'
  get '/groups/:group_id/map' => 'maps#index_for_map', :as => 'group_maps'

  resources :imports do
    member do
      get 'maps'
      get 'start'
      get 'status'
    end
  end
   
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :encryptable, 
    :omniauthable, :omniauth_providers => [ :osm, :mediawiki, :github]
  has_many :permissions
  has_many :roles, :through => :permissions
  
  has_many :my_maps, :dependent => :destroy
  has_many :maps, -> { uniq }, :through => :my_maps
 
  has_many :layers, :dependent => :destroy
  has_many :memberships, :dependent => :destroy
  has_many :groups, :through => :memberships
  
  validates_presence_of    :login
  validates_length_of      :login,    :within => 3..40
  validates_uniqueness_of  :login, :scope => :email, :case_sensitive => false
  
    
  after_destroy :delete_maps
   
  def has_role?(name)
    self.roles.find_by_name(name) ? true : false
  end
  
  def own_maps
    Map.where(["owner_id = ?", self.id])
  end

  def own_this_map?(map_id)
    Map.exists?(:id => map_id.to_i, :owner_id => self.id)
  end

  def own_this_layer?(layer_id)
    Layer.exists?(:id => layer_id.to_i, :user_id => self.id)
  end
  
  def provider_name
    if provider && provider == "mediawiki"
      "Wikimedia Commons"
    elsif provider && provider == "osm"
      "OpenStreetMap"
    else
      provider
    end
  end
  
  #Called by Devise 
  #Method checks to see if the user is enabled (it will therefore not allow a user who is disabled to log in)
  def active_for_authentication?
    super and self.enabled?
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    # Create user if not exists
    unless user
      user = User.create(
        login: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: "#{auth.info.nickname}@twitter.com", # make sure this is unique
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end


  def self.find_for_osm_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    # Create user if not exists
    unless user
      user = User.create(
        login: auth.info.display_name,
        provider: auth.provider,
        uid: auth.uid,
        email: "#{auth.info.display_name}@osm.org", # make sure this is unique
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end
  
   def self.find_for_mediawiki_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid.to_s).first
    # Create user if not exists
    unless user
      user = User.create(
        login: auth.info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: "#{auth.info.name}+warper@mediawiki.org", # make sure this is unique
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end
  
  def self.find_for_github_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid.to_s).first
 
    unless user
      user = User.create(
        login: auth.info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: "#{auth.info.nickname}+warper@github.com", # make sure this is unique
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end
  
protected

  #called after the user has been destroyed
  #delete all user maps
  def delete_maps
    own_maps.each do | map |
      logger.debug "deleting map #{map.inspect}"
      map.destroy
    end
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'
  
  before_filter :authenticate_user!, :only => [:show, :edit, :update]

  before_filter :check_super_user_role, :only => [:index, :destroy, :enable, :disable, :stats, :disable_and_reset]

  rescue_from ActiveRecord::RecordNotFound, :with => :bad_record
  
  helper :sort
  include SortHelper

  def stats
    sort_init "total_count"
    sort_update

    @html_title = "Users Stats"

    the_sql = "select user_id, username, COUNT(user_id) as total_count,
      COUNT(case when auditable_type='Gcp' then 1 end) as gcp_count,

      COUNT(case when auditable_type='Map' or auditable_type='Mapscan' then 1 end) as map_count,

      COUNT(case when action='update' and auditable_type='Gcp' then 1 end) as gcp_update_count,

      COUNT(case when action='create' and auditable_type='Gcp' then 1 end) as gcp_create_count,

      COUNT(case when action='destroy' and auditable_type='Gcp' then 1 end) as gcp_destroy_count

      from audits group by user_id, username ORDER BY #{sort_clause}"


    @users_activity = Audited::Adapters::ActiveRecord::Audit.paginate_by_sql(the_sql,
                                               :page => params[:page],
                                               :per_page => 30)
  end


  def index
    @html_title = "Users"
    sort_init 'email'
    sort_update
    @query = params[:query]
    @field = %w(login email provider).detect{|f| f == (params[:field])}
    if @query && @query.strip.length > 0 && @field
      conditions = ["#{@field}  ~* ?", '(:punct:|^|)'+@query+'([^A-z]|$)']
    else
      conditions = nil
    end
    @users = User.where(conditions).order(sort_clause).paginate(:page=> params[:page], :per_page => 30)

  end

  def index_for_group
    @group = Group.find(params[:group_id])
    @html_title = "Users in Group " + @group.id.to_s
    sort_init 'email'
    sort_update
    @query = params[:query]
    @field = %w(login email provider).detect{|f| f == (params[:field])}
    if @query && @query.strip.length > 0 && @field
      conditions = ["#{@field}  ~* ?", '(:punct:|^|)'+@query+'([^A-z]|$)']
    else
      conditions = nil
    end
    @users = @group.users.where(conditions).order(sort_clause).paginate(:page=> params[:page],
:per_page => 30)
    render :action => 'index'
  end

  def show
    @user = User.find(params[:id]) || current_user
    @html_title = "Showing User "+ @user.login.capitalize
    @mymaps = @user.maps.order("updated_at DESC").paginate(:page => params[:page],:per_page => 8)
    @current_user_maps = current_user.maps
    respond_to do | format |
      format.html {}
      format.js {}
      format.json {render :json => {:stat => "ok",:items => @user.to_a}.to_json(:only =>[:login, :created_at, :stat, :items, :enabled ])  }
    end

  end



  def edit
    @html_title = "Edit User Setttings"
    @user = current_user
  end

  def update
    @user = User.find(current_user)
    if @user.update_attributes(params[:user])
      flash[:notice] = "User updated"
      redirect_to :action => 'show', :id => current_user
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    unless @user.has_role?("administrator") ||  @user.has_role?("super user")
      if @user.destroy
        flash[:notice] = "User successfully deleted"
      else
        flash[:error] = "User could not be deleted"
      end
    else
      flash[:error] = "Admins cannot be destroyed"
    end
    redirect_to :action => 'index'
  end

  def disable_and_reset
    @user = User.find(params[:id])
    if @user.provider?
      flash[:error] = "Sorry, users from other providers are not able to be reset"
      return redirect_to :action => 'show'
    end
    unless @user.has_role?("administrator") ||  @user.has_role?("super user")
      generated_password = Devise.friendly_token.first(8)
      @user.password=generated_password
      @user.password_confirmation=generated_password
      
      if @user.save
        UserMailer.disabled_change_password(@user).deliver 
        @user.send_reset_password_instructions
        flash[:notice] = "User changed and an email sent with password reset link"
      else
        flash[:error] = "Sorry, there was a problem changingin this user"
      end
      
    else
      flash[:error] = "Admins cannot be disabled and reset, sorry"
    end
    
    redirect_to :action => 'show'
  end

  def disable
    @user = User.find(params[:id])
    if @user.update_attribute(:enabled, false)
      flash[:notice] = "User disabled"
    else
      flash[:error] = "There was a problem disabling this user."
    end
    redirect_to :action => 'index'
  end

  def enable
    @user = User.find(params[:id])
    if @user.update_attribute(:enabled, true)
      flash[:notice] = "User enabled"
    else
      flash[:error] = "There was a problem enabling this user."
    end
    redirect_to :action => 'index'
  end

  def bad_record
    respond_to do | format |
      format.html do
        flash[:notice] = "User not found"
        redirect_to root_path
      end
      format.json {render :json => {:stat => "not found", :items =>[]}.to_json, :status => 404}
    end
  end


end

app/views/users/_admin_tools.html.erb
<% if admin_authorized? && current_user != @user-%>
  <div class="user-admin">
    Email : <%= @user.email -%>  <br />
    Enabled? : <%= @user.enabled ? 'Yes' : 'No' -%> <br />
    <br />
    <%= link_to('Delete User', user_path(@user.id), :method => :delete, :confirm => 'Are you sure') -%> This cannot be undone. Removes all their data.<br />

    <% if @user.enabled -%>
      <%= link_to('Disable', disable_user_path(@user.id), :method => :put) -%>
    <% else -%>
      <%= link_to('Enable', enable_user_path(@user.id), :method => :put) -%>
    <% end -%>  the user's account - changeable by admin <br />

<%- unless @user.provider? %>
    <%= link_to "Change and reset password", disable_and_reset_user_path(@user.id), :method => :put %> This changes the password of the users account, and sends link via email to user to create a new password. Until a password is changed, the user cannot login.<br />
<% end %>

    <%= link_to 'Edit roles', user_roles_path(@user) -%> Change roles / groups that the user belongs to
  </div>
<% end -%>

app/views/users/_user.html.erb
<tr class="<%= cycle('table0', 'table1') -%>">
  <td><%= link_to(( h user.login), user_path(user.id), :method => :get)  -%></td>
  <% if admin_authorized? %>
    <td><%=h user.provider -%></td>
    <td><%=h user.email -%></td>
    <td><%= user.enabled ? 'yes' : 'no' -%>&nbsp;
      <% unless user == current_user -%>
        <% if user.enabled -%>
          <%= link_to('disable', disable_user_path(user.id), :method => :put) -%>
        <% else -%>
          <%= link_to('enable', enable_user_path(user.id), :method => :put) -%>
        <% end -%>

      <% end -%>
      &nbsp;
    </td>

    <td><%= link_to 'edit roles', user_roles_path(user) -%></td>
  <% end -%>
</tr>

app/views/users/index.html.erb
<% if admin_authorized? %>
 <%= form_tag url_for(:controller => "users"), :id=>"searchform",:name=> "searchform", :method => :get do -%>
    User Search
    <select id="field" name="field">
      <%= options_for_select([ ["Name", "login"],
          ["Email", "email"],["OAuth Provider", "provider"] ], @field)-%>
    </select>
    for
    <%= text_field_tag 'query', @query -%>
    <input type="submit" value=" Go " />
  <% end -%>
<% end %>
<h2>Users
  <% if @group -%> in Group <%= @group.id.to_s -%>. <% end -%>
  <%if @query && @query.length > 0 %>&mdash; Searched for "<%=@query%>"
  <%end-%></h2>

<%= will_paginate @users %>
<table class="usertable">
  <thead>
    <tr>
      <%= sort_header_tag('login', :title => "Username") %>
      <% if admin_authorized? %>
        <%= sort_header_tag('provider', :title => "OAuth Provider") %>
        <%= sort_header_tag('email', :title => "Email") %>
        <%= sort_header_tag('enabled', :title => "Enabled?") %>
        <th>Roles</th>
      <% end -%>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => "user", :collection => @users %>
  </tbody>
</table>
<%= will_paginate @users %>

app/views/users/show.html.erb
<%= link_to "&lt; Browse Maps".html_safe, maps_path %>

<h2>User: <%=h @user.login %></h2>
<%- if @user.provider %>
<p>A <%= image_tag(@user.provider+'_logo.png', width: '17', height: '17') %> <%=@user.provider_name.titlecase %> User </p>
<%- end %>
<p>Joined on: <%= @user.created_at.to_s(:long) %></p>
<h3>Profile Description:</h3>
<p><%= (h @user.description).gsub("\n","<br/>") %></p>
<p><%=link_to 'User activity', user_activity_url(:id=>@user.id) %></p>
<%= render :partial => 'users/admin_tools', :object => @user %>
<h3>User Maps</h3>

<div id = "usermaps">
  <%=will_paginate @mymaps %>
  <table>
  <%= render :partial => 'maps/map', :collection =>  @mymaps unless @mymaps.nil? %>
</table>
<%= will_paginate @mymaps %>
</div>

app/views/users/stats.html.erb
<h2>User Statistics</h2>

<%= will_paginate @users_activity %>
<table class="usertable">
  <thead>
    <tr>
      <%= sort_header_tag('username', :title => "User") %>
      <%= sort_header_tag('total_count', :title => "Total") %>
      <%= sort_header_tag('map_count', :title => "Total Map Changes") %>
      <%= sort_header_tag('gcp_count', :title => "Total Points Changes") %>
      <%= sort_header_tag('gcp_create_count', :title => "Created Points") %>
      <%= sort_header_tag('gcp_update_count', :title => "Updated Points") %>
      <%= sort_header_tag('gcp_destroy_count', :title => "Deleted Points") %>
      <th>Further Details</th>
    </tr>
  </thead>
  <tbody>

    <% @users_activity.each do | user | %>
      <tr class="<%= cycle('table0', 'table1') -%>">
        <td><% if user.user_id %>
            <%= link_to(user.username, user_path(user.user_id))%>
          <% else %>
            Unknown
          <% end %>
          </td>
        <td><%=user.total_count %></td>
        <td><%=user.map_count %></td>
        <td><%=user.gcp_count %></td>
        <td><%=user.gcp_create_count %></td>
        <td><%=user.gcp_update_count %></td>
        <td><%=user.gcp_destroy_count %></td>
        <td>
          <% if user.user_id %>
            <%= link_to("User Activity", user_activity_path(user.user_id)) %>
          <% else %>
          <% end %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>
<%= will_paginate @users_activity %>