config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about' => 'home#about', :as => 'about'
  get '/help' => 'home#help', :as => 'help'
  
  devise_for :users, :path => 'u',:controllers => { :registrations => "users_registrations", :sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :users do
    member do
      put 'enable'
      put 'disable'
      put 'disable_and_reset'
    end
    collection do
      get 'stats'
    end
    resource :user_account
    resources :roles
  end
  
  get '/maps/activity' => 'audits#for_map_model', :as => "maps_activity"
  
  resources :maps  do
    member do
      get 'map_type'
      get 'export'
      get 'warp'
      get 'clip'
      post 'rectify'
      get 'align'
      get 'warped'
      get 'metadata'
      get 'comments'
      get 'delete'
      get 'status'
      get 'publish'
      get 'unpublish'
      post 'save_mask_and_warp'
      delete 'delete_mask'
      post 'warp_aligned'
      get 'gcps'
      get 'rough_state' => 'maps#get_rough_state'
      post 'rough_state' => 'maps#set_rough_state'
      get 'rough_centroid'=> 'maps#get_rough_centroid'
      post 'rough_centroid' => 'maps#set_rough_centroid'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do
        get 'geosearch'
        get 'tag'
    end
    resources :layers
  end
  
  get '/maps/thumb/:id' => 'maps#thumb', :as =>'thumb_map'
  
  get '/gcps/' => 'gcp#index', :as => "gcps"
  get '/gcps/:id' => 'gcps#show', :as => "gcp"
  delete '/gcps/:id/destroy' => 'gcps#destroy', :as => "destroy_gcp"
  post '/gcps/add/:mapid' => 'gcps#add', :as => "add_gcp"
  put '/gcps/update/:id' => 'gcps#update', :as => "update_gcp"
  put '/gcps/update_field/:id' => 'gcps#update_field', :as => "update_field_gcp"
  

  get '/maps/wms/:id' => "maps#wms", :as => 'wms_map'
  get '/maps/tile/:id/:z/:x/:y' => "maps#tile", :as => 'tile_map'
  
  get '/layers/wms/:id' => "layers#wms", :as => "wms_layer"
  get '/layers/tile/:id/:z/:x/:y' => "layers#tile", :as => 'tile_layer'
  
  resources :layers do
    member do
      get 'comments'
      get 'merge'
      get 'publish'
      get 'toggle_visibility'
      post 'update_year'
      get 'wms'
      get 'wms2'
      get 'maps'
      get 'export'
      get 'metadata'
      get 'delete'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do 
      get 'geosearch'
    end
  end
  
  put '/layers/:id/remove_map/:map_id' => 'layers#remove_map', :as => 'remove_layer_map'
  put '/layers/:id/merge' => 'layers#merge', :as => 'do_merge_layer'
  
  get '/users/:user_id/maps' => 'my_maps#list', :as => 'my_maps'
  post '/users/:user_id/maps/create/:map_id' => 'my_maps#create', :as => 'add_my_map'
  post '/users/:user_id/maps/destroy/:map_id' => 'my_maps#destroy', :as => 'destroy_my_map'

  get '/users/:id/activity' => 'audits#for_user', :as => 'user_activity'
  
  
  get '/maps/acitvity.:format' => 'audits#for_map_model', :as => "formatted_maps_activity"
  get '/maps/:id/activity' => 'audits#for_map', :as => "map_activity"
  get '/maps/:id/activity.:format' => 'audits#for_map', :as => "formatted_map_activity"

  get '/activity' => 'audits#index', :as => "activity"
  get '/activity/:id' => 'audits#show', :as => "activity_details"
  get '/activity.:format' => 'audits#index', :as => "formatted_activity"

  
  resources :comments

  
  resources :groups 
  
  get '/groups/:group_id/users/new' => 'memberships#new', :as => 'new_group_user'
  delete '/groups/:group_id/users/destroy/:id' => 'memberships#destroy', :as => 'destroy_group_user'
  get '/groups/:group_id/users' => 'users#index_for_group', :as => 'group_users'
  get '/groups/:group_id/map' => 'maps#index_for_map', :as => 'group_maps'

  resources :imports do
    member do
      get 'maps'
      get 'start'
      get 'status'
    end
  end
   
  

end

app/views/shared/_addthis.html.erb
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style"
     addthis:title="<%=snippet(title, 20)%>"
     addthis:description="<%=snippet(description, 30)%>" >
  <a href="http://www.addthis.com/bookmark.php?v=250&amp;username=<%=APP_CONFIG['addthis_user']%>"
     class="addthis_button_compact" >Share</a>
  <span class="addthis_separator">|</span>
  <a class="addthis_button_facebook"></a>
  <a class="addthis_button_myspace"></a>
  <a class="addthis_button_google"></a>
  <a class="addthis_button_twitter"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=<%=APP_CONFIG['addthis_user']%>"></script>
<!-- AddThis Button END -->

app/views/shared/_analyticsbottom.html.erb
  <script type="text/javascript">
    try {
      var pageTracker = _gat._getTracker("<%=APP_CONFIG['google_analytics_code'] %>");
      pageTracker._setCookiePath("<%=APP_CONFIG['google_analytics_cookie_path'] %>");
      <%- if @layer -%>
      pageTracker._trackPageview("layers/<%=@current_tab%>/<%=@layer.id%>");
        <%- else -%>
      pageTracker._trackPageview("maps/<%=@current_tab%>/<%=@map.id%>");
        <%- end -%>
    } catch(err) {}</script>

app/views/shared/_analyticstop.html.erb
  <script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  </script>

app/views/shared/_export_window.html.erb
<script type="text/javascript">
  var isHovering = false;
  function closeExportWindow(force) {
    if (!isHovering || force) {
      jQuery('#export_window').hide();
    }
  }
  jQuery(document).ready(function() {

    jQuery("#export_window").hide();
    jQuery("#export_button").click(function() {
      var o = jQuery(this).offset();
      jQuery("#export_window").css({'position': 'absolute', 'left': o.left, 'top': o.top + 17});
      jQuery("#export_window").show();
    });

    jQuery("#export_window").mouseenter(function() {
      isHovering = true;
    }).mouseleave(function() {
      isHovering = false;
      setTimeout('closeExportWindow(false)', 700);
    });

    jQuery("#close_export_window").click(function() {
      closeExportWindow(true);
    });

  });
</script>

<div id="export_toolbox">|&nbsp;
  <a href="#" id="export_button" class="export_button"><%=image_tag("KML-logo-20x25.png", :height => '16')%>&nbsp;Export</a>
  <div id="export_window" class="export_float_div hidden" >
    <div id="export_window_inner">
      <div id="export_window_head">
        <span>Export Links</span>
        <a id="close_export_window" href="#" >X</a>
      </div>
      <div id="export_window_content" style="display: block;">
        <% unless @layer -%>
          <ul>
            <li> <%= link_to(image_tag("KML-logo-20x25.png")+"Download KML file",  map_url(:id => @map, :format => :kml)) %>  </li>
            <li><%= link_to(image_tag("google_maps-20x25.png")+"View KML in Google Maps", "http://maps.google.com?q="+map_url(:id => @map, :format => :kml), :target => "_blank") %> </li>
            <li><%= link_to(image_tag("wms-20x25.png")+"WMS Capabilities URL",url_for(wms_map_url(:id=>@map, :request => "GetCapabilities", :service => "WMS", :version => "1.1.1")) )%> </li>
            <li>
              <% tile_url = url_for(:controller => "maps", :action => "tile", :id => @map, :x => "x", :y => "y", :z => "z", :only_path => false) %>
              <%=link_to image_tag("tiles-20x25.png")+"Tiles base URL", tile_url %> 
            </li>
            <% if user_signed_in? -%>
              <li><%= link_to(image_tag("image-icon-20x25.png")+"Download rectified GeoTiff", export_map_url(:id => @map, :format => :tif)) %> </li>
              <li><%= link_to(image_tag("image-icon-20x25.png")+"Download rectified PNG", export_map_url(:id => @map, :format => :png)) %></li>
              <li>&nbsp;</li>
            <% else -%>
              <li> Log in for</li>
            <% end -%>
            <li> <%= link_to_if(user_signed_in?, "More export options", map_path(:id=> @map,:anchor=>"Export_tab")) -%> </li>
          </ul>
        <% else  -%>
  <%#layer%>
          <ul>
            <li> <%= link_to(image_tag("KML-logo-20x25.png")+"Download KML file",  layer_url(:id => @layer, :format => :kml)) %>  </li>
            <li><%= link_to(image_tag("google_maps-20x25.png")+"View KML in Google Maps", "http://maps.google.com?q="+layer_url(:id => @layer, :format => :kml), :target => "_blank") %> </li>
            <li><%= link_to(image_tag("wms-20x25.png")+"WMS Capabilities", :action=>"wms", :id=>@layer, :request => "GetCapabilities", :service => "WMS", :version => "1.1.1" )%> </li>
            <li>
              <% tile_url = url_for(:controller => "layers", :action => "tile", :x => "x", :y => "y", :z => "z", :only_path => false) %>
              <%=link_to image_tag("tiles-20x25.png")+"Tiles base URL", tile_url %> 
            </li>
            <% unless user_signed_in? -%>
              <li> Log in for</li>
            <% end -%>
            <li> <%= link_to_if(user_signed_in?, "More export options", layer_path(:id=> @layer,:anchor=>"Export_tab")) -%> </li>

          </ul>


        <% end %>
        <div style="clear:both;"></div>
      </div>
      <div id="export_window_foot" style="display: block;">
        MapWarper
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- empty, aww -->

app/views/shared/_header.html.erb
<div class="user_status">
  <% if user_signed_in? %>
    Logged in as:
    <% if current_user.provider? %>
      <%= link_to "#{image_tag(current_user.provider+'_logo.png', width: '17', height: '17', class: 'user_provider')} #{current_user.login.capitalize}".html_safe, user_path(current_user) %>
    <% else %>
      <%= link_to h(current_user.login.capitalize), user_path(current_user) %>
    <% end %>
    <%= link_to "My Maps", my_maps_path(current_user) %>
    <%= link_to "My Activity", user_activity_path(current_user) %>
    <%= link_to "Settings", edit_user_registration_path %>
    <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Log In", new_user_session_path %>
    <%= link_to "Create Account", new_user_registration_path %>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role?("administrator") || current_user.has_role?("super user") %>
      <br />
      <%= link_to "All Maps", maps_path %>
      <%= link_to "All Mosaics", layers_path %>
      <%= link_to "All Activity", activity_path %>
      <%= link_to "All Comments", comments_path %>
      <%= link_to "Groups", groups_path %>
      <%= link_to "Imports", imports_path %>
      <%= link_to "User Stats", stats_users_path %>
      <%= link_to "Administer Users", users_path %>
    <% end %>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<div id="nav">
  <ul id="navlist">
    <li><%= link_to_unless_current("Home", root_path) { "<span>Home</span>".html_safe } %></li>
    <li><%= link_to_unless((current_page?(maps_url) && !current_page?(maps_url(:show_warped =>1))),"Browse All Maps", maps_url) { "<span>Browse All Maps</span>".html_safe } %></li>
    <li><%= link_to_unless_current("Upload Map", new_map_path) { "<span>Upload Map</span>".html_safe } %></li>
    <li><%= link_to_unless_current("Browse All Mosaics",  layers_path) { "<span>Browse All Mosaics</span>".html_safe } %></li>
    <li><%= link_to_unless_current("Add Mosaic", new_layer_path) { "<span>Add Mosaic</span>".html_safe } %></li>
    <li><%= link_to_unless_current("About", about_path) { "<span>About</span>".html_safe } %></li>
    <li><%= link_to_unless_current("Help", help_path) { "<span>Help</span>".html_safe } %></li>
  </ul>
</div>

app/views/shared/_search.html.erb
<%= form_tag url_for(:controller => "maps"), :id=>"searchform",:name=> "searchform", :method => :get do -%>
  Search  
  <select id="field" name="field">
    <%= options_for_select([ ["Title", "title"], 
        ["Description", "description"], 
        ["Publisher", "publisher"],
        ["Author", "authors"],
        ["Tags", "tags"]], @field)-%>
  </select>
  for 
  <%= text_field_tag 'query', @query -%>
  <input type="submit" value=" Go ">
  <% if @show_warped == "1" -%>
    <% check_all = false -%>
    <% check_rectified = true -%>
  <% else -%>
    <% check_all = true -%>
    <% check_rectified = false -%>
  <% end %>

  <label for="all_maps">All maps</label>
  <%= radio_button_tag('show_warped', 0, check_all, :id => 'all_maps') %>
  <label for="rectified_maps">Rectified maps only</label>
  <%= radio_button_tag('show_warped', 1, check_rectified, :id => 'rectified_maps') %>

<% end -%>
  <br />
  New: <%= link_to 'Find Rectified Maps by Location',  url_for(:controller => 'maps', :action=>'geosearch'), :class => "buttonWarper" %>

app/views/shared/_sort.html.erb
Sort By:
<%= sort_header_tag('title', :title => "Title") %>
&nbsp;|&nbsp;
<%= sort_header_tag('updated_at', :title => "Last modified") %>
&nbsp;|&nbsp;
<%= sort_header_tag('status', :title => "Status") %>